spring:
  application:
    name: zuul-server
server:
  port: 8766
  address: 127.0.0.1
eureka:
  instance:
    hostname: localhost
  client:
    eureka-server-u-r-l-context: http://${eureka.instance.hostname}:8761/eureka/,http://${eureka.instance.hostname}:9761/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: feign-server